version: "3"

services:
  server:
    build: ./server/
    command: python ./manage.py runserver 8080
    ports:
      - "1234:1234"
  client:
    build: ./client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server
